version: '3.8'

services:
  mysql-dev:
    image: mysql
    container_name: mysql-dev
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234